
// This file has been generated by the GUI designer. Do not modify.
namespace ILSpyGui
{
	public partial class TreeView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ILSpyGui.TreeView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ILSpyGui.TreeView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
